### ISSUE TITLE
Is it possible to use the pre-calculated linkage matrix?

### ISSUE THREAD

**Issue by liuzj039** [Marsilea-viz/marsilea#11]
Amazing visualization package. 
I was wondering if it is possible to use a precomputed linkage matrix in the `add_dendrogram` function, similar to the row (col) linkage parameter in `seaborn.clustermap`? 
Thank you very much for your help.

**Comment by Mr-Milk** [comment]
Nice suggestion, this should be a simple feature. I'll add it to the next release.

**Comment by liuzj039** [comment]
Thank you very much for your prompt response.  I am eagerly anticipating the upcoming updates.

**Comment by Mr-Milk** [comment]
You may try the new dev version, a new parameter `linkage` is added to the `add_dendrogram` method

To install the dev version directly from GitHub

```shell
pip install git+https://github.com/Marsilea-viz/marsilea.git
```

**Comment by liuzj039** [comment]
It worked very well. Thank you very much for your help."
