### ISSUE TITLE
Add Numbers to heatmap

### ISSUE THREAD

**Issue by demian1** [Marsilea-viz/marsilea#22]
Thank you so much for this amazing package!

I am not sure if this might already be possible with the current version, but it would be amazing if instead of adding markers to a heatmap, we could display the actual values on top of the heatmap.

Thanks a lot!

**Comment by Mr-Milk** [comment]
Thanks for using Marsilea! 

There are two ways to achieve this:
1. Pass `annot=True` to `Heatmap`, this is the same as seaborn.
2. There is a hidden plotter called `TextMesh` (not documented yet), you can use `.add_layer()` to add `TextMesh` on top of the heatmap, this will give you finer control over the style etc.

I'm trying to improve the documentation these days, feel free to ask questions or give suggestions!

**Comment by demian1** [comment]
@Mr-Milk Thanks so much ! The TextMesh solution worked perfectly.
