### ISSUE TITLE
Free Font Awesome icons not rendering

### ISSUE THREAD

**Issue by aadimator** [Marsilea-viz/marsilea#23]
I've trying to render the Font Awesome Icons using mpl_fontkit and the examples provided on the website. The icons in the example work fine, but when I change the utf8 to some other "Free" icon, it doesn't show. It just shows a blank box. I've tried several icons, all free, and they don't work. I've tried a couple of "Brands" icons as well, and they seem to be working fine. I have no idea what the problem could be. 

Here's a basic program for reproducible problem:
```py
import marsilea as ma
import marsilea.plotter as mp
import mpl_fontkit as fk
import numpy as np

fk.install_fontawesome(verbose=False)

data = np.random.randint(0, 3, 10)

# mapper = {0: '\uf58a', 1: '\uf11a', 2: '\uf567'}
mapper = {0: '\uf183', 1: '\uf182', 2: '\uf221'}
cmapper = {0: '#609966', 1: '#DC8449', 2: '#F16767'}
flavour = [mapper[i] for i in data]
flavour_colors = [cmapper[i] for i in data]
labels = mp.Labels(flavour, fontfamily='Font Awesome 6 Free',
              text_props={'color': flavour_colors})
_, ax = plt.subplots()
labels.render(ax)
```

And the output is:
![image](https://github.com/Marsilea-viz/marsilea/assets/10383542/fbf230aa-10a2-4863-97a4-b32fd69c5093)

When I uncomment the original icons as specified in the Oil example, they seem to be working fine: 
![image](https://github.com/Marsilea-viz/marsilea/assets/10383542/f716eb30-3667-4159-a1c2-26eaf09992a2)

But changing the utf8 values produces the above output. Can you tell me what I'm doing wrong here?

**Comment by Mr-Milk** [comment]
You need to add `fontweight=900` to display it, notice that it must be this exact number.

```python
import mpl_fontkit as fk
import matplotlib.pyplot as plt

fk.install_fontawesome(verbose=False)

plt.text(.5, .5, "\uf183\uf182\uf221", fontfamily="Font Awesome 6 Free", fontweight=900)
```
And you get:
![image](https://github.com/Marsilea-viz/marsilea/assets/23433306/a057f12e-50a6-49e9-86ca-9d8727c56c33)

In case you want to know, Font awesome distributed the "Free" font in two styles, weight 400 and weight 900. Unfortunately, it's not way for us to tell which icon is available in which style. So if you find something doesn't work, try either `fontweight=400` or `900`. However, if one of your glyph is in 400 and one is in 900, and you want to plot them together, it won't be easy. But that's what we can get for a free version.

**Comment by aadimator** [comment]
Thanks a bunch. That solved the issue for me.
