### ISSUE TITLE
Add text inside Colors

### ISSUE THREAD

**Issue by aadimator** [Marsilea-viz/marsilea#26]
Is there a way to achieve something like below using `Colors` or some other plotter?

![image](https://github.com/Marsilea-viz/marsilea/assets/10383542/e0faf330-0d0b-4126-9a80-d1cc249aa065)

I tried using `Colors` and `TextMesh` but haven't been able to figure out how to make them work together like this.

**Comment by aadimator** [comment]
Perfect. I thought we can only use `Chunk` once for a given split. It works in this scenario, but in case where I can't split the plot, is there another way to achieve it, or is this the only way for now? 

Again, thanks for the help. It's really appreciated.

**Comment by Mr-Milk** [comment]
Yes, the `Chunk` can be used multiple times. Can you give an example of when you can't split the plot but want to add text? 
I'm not sure if this is what you want, but if you want to label multiple splits with the same name, a `FixedChunk` allows you to merge multiple chunks, the downside is that it will not reorder if you add a dendrogram.

**Comment by aadimator** [comment]
![image](https://github.com/Marsilea-viz/marsilea/assets/10383542/1457a170-9f0d-4647-9443-ed2d128ee316)

Let's say that in the above plot, I've split based on TME, and I also want to add some text on the Biopsy location row or Surgery row (could be its label, or the number of samples or anything else). Can I achieve that in any way?

**Comment by Mr-Milk** [comment]
In the current Marsilea, this is impossible. In Surgery, you have green blocks in two places, so it's difficult to tell where to put the text. But if you really want this feature, you can implement your own `RenderPlan`.

If you want to add extra text, I would add it to the label, something like **Surgery (Yes: 10, No: 20)**.

By the way, if you plan to use Marsilea in a publication, please consider citing our preprint, it will help a lot in keeping this project alive, https://doi.org/10.1101/2024.02.14.580236

**Comment by aadimator** [comment]
Yes, I understand that the above example wasn't a perfect one (just sent a screenshot of whichever one was readily available at that time). 

Sure thing. I'll definitely cite it if I use it in my publication. Thanks for such a great tool.
