### ISSUE TITLE
Dot plot example?

### ISSUE THREAD

**Issue by ivirshup** [Marsilea-viz/marsilea#27]
I've been struggling to figure out how to make a [scanpy-style dot plot](https://scanpy.readthedocs.io/en/stable/generated/scanpy.pl.dotplot.html) with Marsilea, though it seems like this should be possible.

Could an example of this kind of plot be added to the documentation?

**Comment by Mr-Milk** [comment]
Thank you for using the Marsilea. I've included an example below for you to refer to. Feel free to ask or open a new issue if anything is unclear.

The current documentation is a bit unclear. I will try to add more content and make it easier for new users in the next few months.

```python
import numpy as np
import marsilea as ma
import marsilea.plotter as mp

# Synthetic data
color = np.random.randn(10, 10)
size = np.random.randn(10, 10)
genes = [f"gene_{i+1}" for i in range(10)]
cells = [f"cell_{i+1}" for i in range(10)]
chunks = ["T cell", "B cell", "myeloid"]
labels = np.random.choice(chunks, 10)

# Do the plotting
dot = ma.SizedHeatmap(size=size, color=color, cluster_data=size, cmap="Reds", 
                      size_legend_kws=dict(title="Size Title"),
                      color_legend_kws=dict(title="Color Title")
                     )
# Add labels
dot.add_bottom(mp.Labels(genes), pad=.1)
dot.add_left(mp.Labels(cells), pad=.1)
# Add dendrogram
dot.add_dendrogram("right", method="ward")
# Add group labels
dot.vsplit(labels=labels, order=chunks)
dot.add_top(mp.Chunk(chunks, ["#90D26D", "#912BBC", "#496989"]))
# Add legends
dot.add_legends()
dot.render()
```
![image](https://github.com/Marsilea-viz/marsilea/assets/23433306/2da77c98-9a43-408e-ade2-d62dcee65cfe)
