### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by gh-sgordon** [Marsilea-viz/marsilea#34]
pip install marsilea
ERROR: Could not find a version that satisfies the requirement marsilea (from versions: none)
ERROR: No matching distribution found for marsilea

**Comment by Mr-Milk** [comment]
Marsilea is a pure Python package,  there shouldn't be any problem with installation. Could you please share your system and Python environment info.

**Comment by gh-sgordon** [comment]
sorry, my mistake.  I am still getting an error, however, with the oncoprint example:
import marsilea as ma
import marsilea.plotter as mp
import oncoprinter.OncoPrint as op

ModuleNotFoundError: No module named 'oncoprinter'

**Comment by Mr-Milk** [comment]
Oncoprinter is supposed to included in the distribution, but may be excluded somehow. I will need some time to dig it through. Meanwhile, we have a separate package called oncoprinter, you can do 'pip install oncoprinter' to install it, but it's not updated.

**Comment by Mr-Milk** [comment]
I checked for distribution of Marsilea, the oncoprinter is included if you install the latest version.
You should import oncoprint like below, it's a class but not a module

```python
from oncoprinter import OncoPrint
```

If you have further issues after upgrading to the latest version, please let me know.

**Comment by jiaozhuolei** [comment]
pip install marsilea
ERROR: Could not find a version that satisfies the requirement marsilea (from versions: none)
ERROR: No matching distribution found for marsilea
“I encountered a similar issue. My Python version is 3.7.13.”
