### ISSUE TITLE
`get_colormap` fails fue to API changes in `matplotlib == 3.9.0`

### ISSUE THREAD

**Issue by PauBadiaM** [Marsilea-viz/marsilea#35]
Hi @Mr-Milk,

Just letting you know that with the recent `matplotlib == 3.9.0` they have deprecated the method `get_cmap`, see [here](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.9.0.html#top-level-cmap-registration-and-access-functions-in-mpl-cm), which makes the function `get_colormap` fail: https://github.com/Marsilea-viz/marsilea/blob/main/src/marsilea/utils.py#L71

**Comment by Mr-Milk** [comment]
Thanks for reporting this, I will make a new hot-fix release in the next few days.
