### ISSUE TITLE
How to display the x-axis label in a stacked bar chart?

### ISSUE THREAD

**Issue by z626093820** [Marsilea-viz/marsilea#40]
from marsilea.plotter import StackBar
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

_, ax2 = plt.subplots()
StackBar(dfbar2,show_value=True).render(ax2)

![image](https://github.com/user-attachments/assets/1806af66-f358-4558-89b7-e77bde8aa29b)

How to display the x-axis label in a stacked bar chart? THANK YOU! such as blew
![image](https://github.com/user-attachments/assets/55e9d79f-c9eb-4e0a-93cf-9a81de6f7051)

**Comment by Mr-Milk** [comment]
Hi, thanks for using Marsilea.

Most of the time you don't need to touch matplotlib APIs in Marsilea. You always initiate a canvas object in Marsilea and then add things on top of it. This will give you much more flexible controls, you can add the labels on either the bottom or top, and you can easily control the size and padding of all your plotters. Hope you have fun using Marsilea!

```python
import numpy as np
import pandas as pd

import marsilea as ma
import marsilea.plotter as mp

data = np.random.randint(1, 10, (10, 10))
labels = [f"Label_{i+1}" for i in range(10)]

b = ma.WhiteBoard(width=8)
b.add_layer(mp.StackBar(pd.DataFrame(data)))
b.add_bottom(mp.Labels(labels, rotation=0), pad=.1)
b.add_top(mp.Labels(labels, rotation=0), pad=.1)
b.render()
```
![image](https://github.com/user-attachments/assets/260e9e55-5f7e-488f-91a9-9859dc6f052e)

**Comment by z626093820** [comment]
> Hi, thanks for using Marsilea.
> 
> Most of the time you don't need to touch matplotlib APIs in Marsilea. You always initiate a canvas object in Marsilea and then add things on top of it. This will give you much more flexible controls, you can add the labels on either the bottom or top, and you can easily control the size and padding of all your plotters. Hope you have fun using Marsilea!
> 
> ```python
> import numpy as np
> import pandas as pd
> 
> import marsilea as ma
> import marsilea.plotter as mp
> 
> data = np.random.randint(1, 10, (10, 10))
> labels = [f"Label_{i+1}" for i in range(10)]
> 
> b = ma.WhiteBoard(width=8)
> b.add_layer(mp.StackBar(pd.DataFrame(data)))
> b.add_bottom(mp.Labels(labels, rotation=0), pad=.1)
> b.add_top(mp.Labels(labels, rotation=0), pad=.1)
> b.render()
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/23433306/356865300-260e9e55-5f7e-488f-91a9-9859dc6f052e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNjk5OTIsIm5iZiI6MTcyMzM2OTY5MiwicGF0aCI6Ii8yMzQzMzMwNi8zNTY4NjUzMDAtMjYwZTllNTUtNWY3ZS00ODhmLTkxYTktOTg1OWRjNmYwNTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDA5NDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkM2NkNDAzYTgyZGFkNDYxMmZjYTJjZTFhMzgxNThiOWQ0NzkwZWZkMzRhZWVmMGE0YzJkOTM4NGEwNGRmOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2-tJxykSIk8azl8DL-qjzZ3CEzy0J7iLdzMP5qtZsWQ)

THANK YOU!
