### ISSUE TITLE
`cut_rows` affects the color of `mp.Numbers`

### ISSUE THREAD

**Issue by SunYong0821** [Marsilea-viz/marsilea#43]
if I didnt use `cut_rows`:
```
sb = mp.StackBar(t_p*100, colors=['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#c49c94', '#f7b6d2', '#c7c7c7', '#dbdb8d', '#9edae5'], width=.8, orient="h")
gc_numbers = mp.Numbers(group_count, color=['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#c49c94', '#f7b6d2', '#c7c7c7', '#dbdb8d', '#9edae5'])
cb = ma.ClusterBoard(t_p.T, height=4, margin=.5)
cb.add_layer(sb)
cb.add_right(gc_numbers, size=1.1, pad=.25)
cb.render()
```
![微信截图_20240905091327](https://github.com/user-attachments/assets/7778a830-8c08-4a3e-8746-41aeb3de594e)

if i use `cut_rows`:
```
sb = mp.StackBar(t_p*100, colors=['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#c49c94', '#f7b6d2', '#c7c7c7', '#dbdb8d', '#9edae5'], width=.8, orient="h")
gc_numbers = mp.Numbers(group_count, color=['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#c49c94', '#f7b6d2', '#c7c7c7', '#dbdb8d', '#9edae5'])
cb = ma.ClusterBoard(t_p.T, height=4, margin=.5)
cb.add_layer(sb)
cb.add_right(gc_numbers, size=1.1, pad=.25)
cb.cut_rows([4,7,9], spacing=.03)
cb.render()
```
![微信截图_20240905091408](https://github.com/user-attachments/assets/45086cec-b41c-47d5-9851-d59dc31ceb4e)

why?

**Comment by Mr-Milk** [comment]
The `color` parameter in `Numbers` is designed to accept only a single color as indicated in the documentation. Although it works if you supply multiple colors, the behavior is not guaranteed. If you want to customize each color, please use `Bar` and check the last example https://marsilea.readthedocs.io/en/stable/api/APIs/marsilea.plotter.Bar.html

**Comment by SunYong0821** [comment]
> The `color` parameter in `Numbers` is designed to accept only a single color as indicated in the documentation. Although it works if you supply multiple colors, the behavior is not guaranteed. If you want to customize each color, please use `Bar` and check the last example https://marsilea.readthedocs.io/en/stable/api/APIs/marsilea.plotter.Bar.html`Numbers`中的`color`参数设计为仅接受文档中指示的单一颜色。虽然如果您提供多种颜色它可以工作，但不能保证其行为。如果您想自定义每种颜色，请使用`Bar`并检查最后一个示例https://marsilea.readthedocs.io/en/stable/api/APIs/marsilea.plotter.Bar.html

It seems that it's not quite working either.
![微信截图_20240905135513](https://github.com/user-attachments/assets/afd87145-5991-49cf-b071-a36c0a125829)

**Comment by SunYong0821** [comment]
> The `color` parameter in `Numbers` is designed to accept only a single color as indicated in the documentation. Although it works if you supply multiple colors, the behavior is not guaranteed. If you want to customize each color, please use `Bar` and check the last example https://marsilea.readthedocs.io/en/stable/api/APIs/marsilea.plotter.Bar.html

group_rows, cut_rows and hsplit，It appears that these three features seem identical, but do they have any differences?

**Comment by Mr-Milk** [comment]
This is what you want:

```python
import marsilea as ma
import marsilea.plotter as mp
import numpy as np

data = np.random.randn(4, 4)

h = ma.Heatmap(data)
h.add_right(mp.Bar([1,2,3,4], palette=["r", "g", ".1", ".8"]))
h.cut_rows([2])
h.render()
```

![image](https://github.com/user-attachments/assets/38119ec1-0b38-4b21-92e0-b06bd27ba7bc)

**Comment by Mr-Milk** [comment]
@SunYong0821 As of v0.4.6, you can use multiple colors for `color` in `Numbers`.

Hope you enjoy Marsilea!

```python
import marsilea as ma
import marsilea.plotter as mp
import numpy as np

data = np.random.randn(4, 4)

h = ma.Heatmap(data)
h.add_right(mp.Numbers([1, 2, 3, 4], color=["r", "g", ".1", ".8"]))
h.cut_rows([2])
h.render()
```
![image](https://github.com/user-attachments/assets/ed0c6f6f-52ed-49e0-b978-0c23a7ca6d51)

**Comment by SunYong0821** [comment]
> > > The `color` parameter in `Numbers` is designed to accept only a single color as indicated in the documentation. Although it works if you supply multiple colors, the behavior is not guaranteed. If you want to customize each color, please use `Bar` and check the last example https://marsilea.readthedocs.io/en/stable/api/APIs/marsilea.plotter.Bar.html`Numbers`中的`color`参数设计为仅接受文档中指示的单一颜色。虽然如果您提供多种颜色它可以工作，但不能保证其行为。如果您想自定义每种颜色，请使用`Bar`并检查最后一个示例https://marsilea.readthedocs.io/en/stable/api/APIs/marsilea.plotter.Bar.html
> > 
> > 
> > group_rows, cut_rows and hsplit，It appears that these three features seem identical, but do they have any differences?group_rows、cut_rows 和 hsplit，看起来这三个功能看起来相同，但是它们有什么区别吗？
> 
> Regarding this, `hsplit` and `vsplit` are deprecated, you should see a warning when you use them. `group_rows` can split by given labels and order, `cut_rows` can split only by the index of row.关于这一点， `hsplit`和`vsplit`已被弃用，您在使用它们时应该会看到警告。 `group_rows`可以按给定的标签和顺序进行拆分， `cut_rows`只能按行的索引进行拆分。

OK  thx

**Comment by SunYong0821** [comment]
> @SunYong0821 As of v0.4.6, you can use multiple colors for `color` in `Numbers`.
> 
> Hope you enjoy Marsilea!
> 
> ```python
> import marsilea as ma
> import marsilea.plotter as mp
> import numpy as np
> 
> data = np.random.randn(4, 4)
> 
> h = ma.Heatmap(data)
> h.add_right(mp.Numbers([1, 2, 3, 4], color=["r", "g", ".1", ".8"]))
> h.cut_rows([2])
> h.render()
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/23433306/365456928-ed0c6f6f-52ed-49e0-b978-0c23a7ca6d51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NTA0MzQsIm5iZiI6MTcyNTg1MDEzNCwicGF0aCI6Ii8yMzQzMzMwNi8zNjU0NTY5MjgtZWQwYzZmNmYtNTJlZC00OWUwLWI5NzgtMGMyM2E3Y2E2ZDUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDAyNDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMWEwM2M2NTljOGE1Y2FhMmY3M2Y3MTFjOGYyYTJmYTliNDQ5MmYyZGUwMzQ4OTBjNDNlZjZkNGQ0NzlhNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.smMhBfhbdb_q3BxyToKsaRm7irIDqQrc_cijvz8bNNs)

I test it pefect!~   thx~
![微信截图_20240909104930](https://github.com/user-attachments/assets/36e4872a-ada2-482b-a0a0-44446ebc875b)
