### ISSUE TITLE
How to load datasets?

### ISSUE THREAD

**Issue by pxxiao-hz** [Marsilea-viz/marsilea#44]
for example: 
```
seq = ma.load_data("seq_align")
seq = seq.iloc[:, 130:175]
```
How can we visualize our own data? What is the corresponding syntax?

Best wishes.

**Comment by pxxiao-hz** [comment]
If the length is 200, how can we visualize with 50 characters per row?

**Comment by Mr-Milk** [comment]
Thanks for using Marsilea. 

1. `lode_data` is for loading example datasets from web. It's not for user to load their own data. For different plotter, there are different input, mostly are either `numpy.ndarray` or `pandas.DaraFrame` or arbitrary array-like container. Please refer to the documentation for details.

2. I assume you want to draw the sequence logo. You can draw each 50 characters separately and then concatenate them. https://marsilea.readthedocs.io/en/stable/tutorial/concatenation.html

**Comment by pxxiao-hz** [comment]
The issue has been resolved. Thanks for your reply.
