### ISSUE TITLE
Arranging canvases in a grid

### ISSUE THREAD

**Issue by jpintar** [Marsilea-viz/marsilea#48]
### Problem/New Plotter

Main canvases can be arranged into rows or columns for rendering, but is it possible to arrange them in a grid?

If we have the following:
```
data1 = np.random.randn(5, 5)
data2 = np.random.randn(3, 10)
data3 = np.random.randn(10, 4)
data4 = np.random.randn(7, 7)

m1 = ma.Heatmap(data1, width=5, height=5)
m2 = ma.Heatmap(data2, width=10, height=3)
m3 = ma.Heatmap(data3, width=4, height=10)
m4 = ma.Heatmap(data4, width=7, height=7)
```
Then `((m1 + 1 + m2) / 1 / m3).render()` works, but `((m1 + 1 + m2) / 1 / (m3 + 1 + m4)).render()` fails with `AttributeError: 'CompositeCrossLayout' object has no attribute 'remove_legend_ax'`. Is there a way around this?

**Comment by Mr-Milk** [comment]
This is out of scope for the current implementation. But it's possible to implement this feature. Do you mind telling me your use case to show why you want to arrange things in a grid layout?

**Comment by Mr-Milk** [comment]
Thanks for sharing your thoughts. I'm open to implement such feature but maybe a different API. For your current visualization purpose, it maybe easier to just simply assemble each heatmap in a vector editor like Illustrator or Inkscape.

BTW, I need to experiment a bit to see the feasibility. I will keep you posted.

**Comment by Mr-Milk** [comment]
The level of uncertainty in the grid layout makes it too complicated to implement. In Marsilea, the size of the figure and the plots are both not deterministic before rendering. In an incremental system like cross-layout, the position and the size of each plot can be easily solved, however, with multiple indeterministic systems, and the fact that we need to consider the possibility of overlap, it becomes too complicated.

However, if you could frame the grid layout problem with more constraints, it may have the chance. Feel free to reopen it if you have further ideas, I will close this issue for now.
