### ISSUE TITLE
Missing color blocks on chunks

### ISSUE THREAD

**Issue by spatts14** [Marsilea-viz/marsilea#52]
### Describe the issue

Missing color blocks on chunks

### Code for reproduction

```Python

h = ma.Heatmap(df, cmap="Reds", label="Expression", height=3, width=4)
h.group_rows(adata_subset.obs["new_clusters_fibro_extended"])

chunk = mp.Chunk(order, rotation=0, align="center")
colors = mp.Colors(adata_subset.obs["new_clusters_fibro_extended"], palette=re_cluster_colors_palette_extended_dict)

h.add_left(colors, size=0.5, pad=0.3)
h.add_left(chunk)
#h.add_bottom(ma.plotter.Labels(df.columns))

h.add_title(f"Expression of genes of interest in fibroblast subsets ({subset} mice)")
h.add_legends()
h.render()



```

### Actual outcome

See below (image wouldn't attach)

### Expected outcome

I don’t know why Im not seeing the color blocks on the left like the tutorial. I can generate tutorial plots fine so I know it isn't an install bug. Can you please help me understand what Im doing wrong in the syntax? 

### Marsilea Version

import marsilea; print(marsilea.__version__)

**Comment by spatts14** [comment]
![f263ec4b-cf7e-4f52-a1ee-eaadd48c145f](https://github.com/user-attachments/assets/026649e5-1309-4710-8108-4a95433c2ced)

**Comment by Mr-Milk** [comment]
Hi Sara, thanks for using Marsilea. This is expected behavior.

In `Chunk`, you need to specify the `fill_colors` parameter to have color or colors in the background. Please see [Chunk](https://marsilea.readthedocs.io/en/stable/api/APIs/marsilea.plotter.Chunk.html).

**Comment by Mr-Milk** [comment]
By the way, did you change some default matplotlib settings? Because the colorbar for the heatmap is gone.

**Comment by spatts14** [comment]
I didn't change anything in the default matplotlib. I also was wondering why that occurred... 
Additionally, I added the fill_colors but I thought by default I shou
![Screenshot 2024-11-12 at 1 59 46 PM](https://github.com/user-attachments/assets/f4ca2e88-4833-4c2b-aff1-9d4b5a454b70)
ld get color blocks in between the labels and heat map like this

**Comment by spatts14** [comment]
Instead when I add a list of colors to fill_color I get this

```
order = ["Alveolar_1", "Alveolar_2", "Peribronchial", "Adventitial_1", "Adventitial_2", "Pericytes"]
colors_list = ["#4A90E2", "#F5A623", "#50E3C2", "#9013FE", "#FF6B6B", "#4A4A4A"]


h = ma.Heatmap(df, cmap="Reds", label="Expression", height=3, width=4)
h.group_rows(adata_subset.obs["new_clusters_fibro_extended"])

chunk = mp.Chunk(order, rotation=0, align="center", fill_colors=colors_list)
colors = mp.Colors(adata_subset.obs["new_clusters_fibro_extended"])

h.add_left(colors, size=0.5, pad=0.3)
h.add_left(chunk)
#h.add_bottom(ma.plotter.Labels(df.columns))

h.add_title(f"Expression of genes of interest in fibroblast subsets ({subset} mice)")
h.add_legends()
h.render()
```

<img width="1076" alt="Screenshot 2024-11-12 at 2 00 29 PM" src="https://github.com/user-attachments/assets/76e65a31-736a-4643-95ac-0c1cc492bd21">

**Comment by spatts14** [comment]
Also I corrected the issue title to remove bug as I think there is something I am not understanding or doing wrong?

**Comment by Mr-Milk** [comment]
I think you are confused with two plotters `Colors` and `Chunk`, `Colors` is to visualize categorical data on each row or column as colors. `Chunk` will span multiple rows or columns to serve as a subtitle-like purpose. If you want to visualize continuous data to replace `Colors`, please use `ColorMesh`.

You can check out the gallery at https://marsilea.readthedocs.io/en/stable/examples/index.html to have an idea on what each plotter does.
