### ISSUE TITLE
[BUG]: Adding Colors layer reflects plot

### ISSUE THREAD

**Issue by jpintar** [Marsilea-viz/marsilea#53]
### Describe the bug

Consider the following plot:
```
data = np.array([[6, 7, 8], [7, 1, 2], [8, 9, 3]])
m = ma.Heatmap(data, cmap='viridis')
m.render()
```
As expected, this yields
![image](https://github.com/user-attachments/assets/1cf83621-cbba-4803-b820-85ca10c15146)
However, adding a `Colors` layer over the heatmap causes the plot to be reflected along the y-axis.

### Code for reproduction

```Python
m = ma.Heatmap(data, cmap='viridis')
c = mp.Colors((data > 5).astype(int), palette={0: 'black', 1: 'lightgray'})
m.add_layer(c)
m.render()
```

### Actual outcome

![image](https://github.com/user-attachments/assets/f6d7e5e3-3c54-4e57-bffe-62c93c8224ee)

### Expected outcome

![image](https://github.com/user-attachments/assets/5493a1ff-201c-4e3b-b4fb-7aa26f2bbf82)

### Additional information

Interestingly, if one adds a further `MarkerMesh` layer, the plot is once again correctly oriented:
```
m = ma.Heatmap(data, cmap='viridis')
c = mp.Colors((data > 5).astype(int), palette={0: 'black', 1: 'lightgray'})
mm = mp.MarkerMesh((data > 5), marker='*', color='red')
m.add_layer(c)
m.add_layer(mm)
m.render()
```
![image](https://github.com/user-attachments/assets/7146f1a6-8f3f-4567-80ae-e92461f038b3)

### Marsilea Version

0.4.6

**Comment by Mr-Milk** [comment]
Interesting... I will have a Quick Look🧐

**Comment by Mr-Milk** [comment]
The problem is that all mesh plotters invert the y-axis anyway. That's why the first Heatmap is correct, the second is wrong, and the third is correct again. Now, the axis will not be flipped again if it's already flipped. This will be available in the next release (ideally, next week, I finally have time to work on Marsilea thanks to the Christmas holiday).
